FROM node:20-alpine as builder

ARG VITE_API_URL=https://po-educacional-production-5497.up.railway.app
ENV VITE_API_URL=${VITE_API_URL}

WORKDIR /app

COPY frontend/package*.json ./
RUN npm ci

COPY frontend/ .
RUN npm run build

FROM node:20-alpine

WORKDIR /app
RUN npm install -g serve

COPY --from=builder /app/dist ./dist

CMD ["serve", "-s", "dist", "-l", "8080"]

